### ISSUE TITLE
Need a "Try this app" button on all app info pages

### ISSUE THREAD

**Issue by rossmounce** [Scifabric/crowdcrafting.org#20]
(When not signed-in)
If user clicks on an app from http://crowdcrafting.org/app/ to get more info about an app, it's a frustrating and un-intuitive dead-end

e.g. one clicks on "Bardomatic" to find out more info about the app.
-> http://crowdcrafting.org/app/bardomatic
The only further clickable link is http://crowdcrafting.org/app/bardomatic/tasks which is confusing.

There is no "Try this app" button on each and every of the 
http://crowdcrafting.org/app/NameOfApp pages. I think there should be such a button here.

**Comment by rufuspollock** [comment]
Hi Ross, I'm going to close this as this is a generic issue and is a dupe or an existing one in main repo (you've already linked it ;-) )

In general, unless very crowdcrafting specific (e.g. just about CC theme or content), I'd recommend creating the issues in the the pybossa repo rather than here.
